### ISSUE TITLE
Update to Videolab 1.3.2!

### ISSUE THREAD

**Issue by Romano-Garmez** [Videolab-Creators-Group/Videopak-Template#1]
[https://github.com/teenageengineering/videolab/releases](https://github.com/teenageengineering/videolab/releases)

I'll get around to this, but it may take me a while.

**Comment by VideolabCreators** [comment]
Thanks Roman! no worries, I’m sure they are sorting more issues out at TE
as well!

**Comment by Romano-Garmez** [comment]
Fixed it!
